import { useEffect, useState } from "react";
import API from "../api";


import FairnessChart from "../components/FairnessChart";
import ExchangePieChart from "../components/ExchangePieChart";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";




function Analytics() {

    const [report, setReport] = useState({});
    const [orders, setOrders] = useState([]);

    useEffect(() => {

        const fetchAnalytics = async () => {

            try {

                const reportRes =
                    await API.get("/fairness/report");

                setReport(reportRes.data);

                const ordersRes =
                    await API.get("/orders");

                setOrders(
                    Array.isArray(ordersRes.data)
                        ? ordersRes.data
                        : []
                );

            } catch (error) {

                console.error(
                    "Error fetching analytics:",
                    error
                );

            }

        };

        fetchAnalytics();

    }, []);

    const generateForensicReport = () => {
        const doc = new jsPDF();
        const user = JSON.parse(localStorage.getItem("user") || "{}");

        // HEADER
        doc.setFillColor(37, 99, 235);
        doc.rect(0, 0, 210, 40, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text("FORENSIC FAIRNESS REPORT", 105, 20, { align: "center" });
        doc.setFontSize(10);
        doc.text(`Generated for: ${user.name || "Authorized Analyst"} | Date: ${new Date().toLocaleDateString()}`, 105, 30, { align: "center" });

        // SYSTEM STATUS
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.text("1. executive Summary", 20, 55);
        doc.setFontSize(11);
        doc.text(`System Rating: ${report.rating || "N/A"}`, 20, 65);
        doc.text(`Fairness Score: ${(report.fairnessScore || 0).toFixed(2)}%`, 20, 72);
        doc.text(`Exchange Balance Score: ${(report.exchangeFairness || 0).toFixed(2)}%`, 20, 79);
        doc.text(`Latency Efficiency Score: ${(report.latencyFairness || 0).toFixed(2)}%`, 20, 86);
        doc.text(`Average System Latency: ${(report.averageLatency || 0).toFixed(2)}ms`, 20, 93);

        doc.setFontSize(16);
        doc.text("2. Intelligent Insights", 20, 110);
        const insightTxt = nseOrders === 0 && bseOrders === 0
            ? "No routing data available. Import order logs to generate insights."
            : (nseOrders > bseOrders
                ? "NSE is currently your dominant liquidity source. We recommend secondary route verification."
                : "BSE shows high utilization. Review routing parity against NSE benchmarks.");
        doc.setFontSize(10);
        doc.text(doc.splitTextToSize(insightTxt, 170), 20, 118);

        autoTable(doc, {
            startY: 135,
            head: [["Exchange", "Volume", "Share %", "Status"]],
            body: [
                ["NSE", nseOrders, `${((nseOrders/report.totalOrders)*100 || 0).toFixed(1)}%`, nseOrders > 0 ? "Active" : "Idle"],
                ["BSE", bseOrders, `${((bseOrders/report.totalOrders)*100 || 0).toFixed(1)}%`, bseOrders > 0 ? "Active" : "Idle"],
            ],
            theme: "striped",
            headStyles: { fillColor: [37, 99, 235] }
        });


        // FOOTER
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text("This report is an automated forensic audit generated by the TORFA Platform.", 105, 285, { align: "center" });

        doc.save(`Forensic_Report_${Date.now()}.pdf`);
    };



    const activeExchanges =
        [...new Set(
            (orders || []).map(
                (order) => order.exchange
            )
        )].length;


    const nseOrders =
        orders.filter(
            order => order.exchange === "NSE"
        ).length;

    const bseOrders =
        orders.filter(
            order => order.exchange === "BSE"
        ).length;

    return (
        <div className="dashboard">
            
            {/* TOP BANNER */}
            <div className="db-banner">
                <div>
                    <h1 className="db-banner-title">Performance Intelligence</h1>
                    <p className="db-banner-desc">
                        A deep-dive into the routing engine's fairness metrics, market distribution, 
                        and historical latency patterns.
                    </p>
                </div>
                <div className="db-avatar" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(255,255,255,0.1)', fontSize: '36px' }}>
                    📊
                </div>
            </div>

            {/* KPI CARDS */}
            <div className="db-kpi-row">
                <div className="db-kpi-card" style={{ borderTop: `4px solid ${report.statusColor || '#2563eb'}` }}>
                    <span className="db-kpi-icon">🛡️</span>
                    <div>
                        <p className="db-kpi-label">System Rating</p>
                        <p className="db-kpi-value" style={{ color: report.statusColor || '#2563eb' }}>{report.rating || "Analyzing..."}</p>
                    </div>
                </div>
                <div className="db-kpi-card" style={{ borderTop: '4px solid #059669' }}>
                    <span className="db-kpi-icon">⚖️</span>
                    <div>
                        <p className="db-kpi-label">Fairness Score</p>
                        <p className="db-kpi-value">{(report.fairnessScore || 0).toFixed(2)}%</p>
                    </div>
                </div>
                <div className="db-kpi-card" style={{ borderTop: '4px solid #7c3aed' }}>
                    <span className="db-kpi-icon">⚡</span>
                    <div>
                        <p className="db-kpi-label">Avg Execution</p>
                        <p className="db-kpi-value">{(report.averageLatency || 0).toFixed(2)}ms</p>
                    </div>
                </div>
                <div className="db-kpi-card" style={{ borderTop: '4px solid #2563eb' }}>
                    <span className="db-kpi-icon">📦</span>
                    <div>
                        <p className="db-kpi-label">Total Throughput</p>
                        <p className="db-kpi-value">{report.totalOrders || 0}</p>
                    </div>
                </div>
            </div>

            {/* FULL WIDTH CHART */}
            <div className="db-panel" style={{ marginBottom: '25px' }}>
                <p className="db-panel-title">📈 Fairness Distribution</p>
                <FairnessChart
                    totalOrders={report.totalOrders}
                    averageLatency={report.averageLatency}
                    fairnessScore={report.fairnessScore}
                />
            </div>

            {/* TWO COL: PIE CHART & SMART INSIGHTS */}
            <div className="db-two-col">
                <div className="db-panel">
                    <p className="db-panel-title">🥧 Exchange Distribution</p>
                    <ExchangePieChart
                        nseOrders={nseOrders}
                        bseOrders={bseOrders}
                    />
                </div>

                <div className="db-panel" style={{ background: 'linear-gradient(145deg, #ffffff, #f8fafc)', border: '1px solid #e2e8f0' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '25px', paddingBottom: '15px', borderBottom: '1px solid #f1f5f9' }}>
                        <div style={{ padding: '12px', background: '#eff6ff', color: '#2563eb', borderRadius: '14px', fontSize: '24px' }}>
                            🧠
                        </div>
                        <h3 style={{ margin: 0, fontSize: '18px', fontWeight: 700, color: '#0f172a' }}>Smart Insights</h3>
                    </div>

                    <div style={{ marginBottom: '20px', background: 'white', padding: '15px', borderRadius: '12px', border: '1px solid #f1f5f9', boxShadow: '0 2px 4px rgba(0,0,0,0.02)' }}>
                        <label style={{ fontSize: '11px', color: '#64748b', textTransform: 'uppercase', letterSpacing: '1px', fontWeight: 700 }}>Strategic Recommendation</label>
                        <p style={{ marginTop: '8px', lineHeight: '1.6', fontSize: '14px', color: '#334155' }}>
                            {nseOrders === 0 && bseOrders === 0 
                                ? "Upload market logs to generate intelligent routing recommendations."
                                : (nseOrders > bseOrders 
                                    ? "NSE is currently your dominant liquidity source. To minimize risk, ensure BSE fallback routes are tested and secondary latency is within 5% of primary."
                                    : "BSE shows high utilization. Current data suggests an 8% higher execution probability on BSE for large-block orders.")
                            }
                        </p>
                    </div>

                    <div style={{ marginBottom: '25px', background: 'white', padding: '15px', borderRadius: '12px', border: '1px solid #f1f5f9', boxShadow: '0 2px 4px rgba(0,0,0,0.02)' }}>
                        <label style={{ fontSize: '11px', color: '#64748b', textTransform: 'uppercase', letterSpacing: '1px', fontWeight: 700 }}>Privacy & Integrity</label>
                        <p style={{ marginTop: '8px', lineHeight: '1.6', fontSize: '14px', fontWeight: 600, color: report.fairnessScore > 90 ? '#059669' : '#d97706' }}>
                            {report.fairnessScore > 90 
                                ? "✅ System is operating at peak efficiency. No systemic routing bias detected in the last session."
                                : "⚠️ Sub-optimal routing detected. Review individual latency logs for potential arbitrage leaks."}
                        </p>
                    </div>

                    <button 
                        style={{ 
                            width: '100%', 
                            padding: '16px', 
                            background: '#2563eb', 
                            color: 'white', 
                            border: 'none', 
                            borderRadius: '12px', 
                            fontWeight: 700, 
                            fontSize: '15px', 
                            cursor: 'pointer',
                            boxShadow: '0 8px 16px rgba(37,99,235,0.25)',
                            transition: '0.2s'
                        }}
                        onMouseOver={(e) => { e.target.style.transform = 'translateY(-2px)'; e.target.style.background = '#1d4ed8'; }}
                        onMouseOut={(e) => { e.target.style.transform = 'translateY(0)'; e.target.style.background = '#2563eb'; }}
                        onClick={generateForensicReport}
                    >
                        📄 Generate Forensic Report
                    </button>
                </div>
            </div>
        </div>
    );

}

export default Analytics;